### ISSUE TITLE
Bug- AttributeError: 'PyCentralDispatchQueue' object has no attribute '_PyCentralDispatchQueue__dispatchOneBlock'

### ISSUE THREAD

**Issue by abhi-shek2000** [mrhappyasthma/PyCentralDispatch#3] opened 2023-05-30 11:12 UTC
I'm hitting an issue while adding multiple blocks to the serial queue,
The first time the function executes properly, the next functions give this error.

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycentraldispatch/thread_pool.py", line 34, in __thread_loop
    currentLambda()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycentraldispatch/py_central_dispatch.py", line 34, in lambda_like_function
    self.__dispatchOneBlock()
AttributeError: 'PyCentralDispatchQueue' object has no attribute '_PyCentralDispatchQueue__dispatchOneBlock'
`

**Comment by mrhappyasthma** [comment] 2023-05-30 22:09
I believe this should be fixed in https://github.com/mrhappyasthma/PyCentralDispatch/pull/4.

**Comment by mrhappyasthma** [comment] 2023-05-30 22:18
I'll be uploading a new package to pypi if you use `pip`. I'll post a link once it's live.

Once it's live, you can use `pip install pycentraldispatch --upgrade`.

**Comment by mrhappyasthma** [comment] 2023-05-30 22:19
It's now live. https://pypi.org/project/pycentraldispatch/1.0.12/

Please test this out and let me know if the issue is fixed. Thanks!

**Comment by mrhappyasthma** [comment] 2023-06-12 02:37
Going to close this out. If you're still having issues, feel free to reopen.

**Closed as completed by mrhappyasthma** 2023-06-12 02:37 UTC
